png(file = "plot3.png", width = 480)
plot(subData$Time, subData$Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
lines(subData$Time, subData$Sub_metering_1, col = "black")
lines(subData$Time, subData$Sub_metering_2, col = "red")
lines(subData$Time, subData$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1,col = c("black", "red", "blue"), cex = 0.7)
dev.off()